Updated FAQ
aws-quickstart/quickstart-documentation-base-common pull request #100
Opened 2020-12-07 22:17 UTC by MarciaRieferJohnston

Edited per AWS style + clarified comments.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-12-07 22:20 UTC, censullo submitted a review, later dismissed

2020-12-08 18:44 UTC, DelfinGala requested changes
I disagree with Acrolinx/AWS's preference for using "of" for cases where using the possessive form is clearer.  "State's stack" is clear as is, partly because it uses two words instead of four to say the same thing. Here's the wording I suggest:

With this setting, the stack's state is retained, and the instance remains running so you can troubleshoot the issue.

2020-12-08 18:58 UTC, MarciaRieferJohnston commented
> I disagree with Acrolinx/AWS's preference for using "of" for cases where using the possessive form is clearer. "State's stack" is clear as is...

I agree. Re-edited. Thanks, Daniel.

2020-12-08 21:17 UTC, DelfinGala approved these changes

2020-12-08 21:24 UTC, censullo approved these changes

2020-12-09 03:21 UTC, merged