Updated for CDK and Terraform Documentation
aws-quickstart/quickstart-documentation-base-common pull request #143
Opened 2021-04-13 20:29 UTC by troy-ameigh

*Description of changes:*

I have added to the CDK support, and then added the same setup for Terraform docs. I have also configured so you can create a 2nd Lang with either. 

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-04-14 02:27 UTC, MarciaRieferJohnston submitted a review, later dismissed

2021-04-23 18:36 UTC, dowen12 approved these changes

2021-04-23 19:08 UTC, MarciaRieferJohnston reviewed
I noted a typo ("Otions") in a comment on `create_repo_structure.sh`. Later learned—at the wonderful Write the Docs conference—that I could suggest the edit in my own commit. So I did that on April 30. Cool.

2021-04-23 19:08 UTC, MarciaRieferJohnston commented on .utils/create_repo_structure.sh
> +#Adds Otions for the following: ((Help/Second Language/CDK/Terraform options) (-h | -l | -c | -t))
"Options" :)

2021-05-01 05:05 UTC, MarciaRieferJohnston commented on .utils/create_repo_structure.sh
> +#Adds Otions for the following: ((Help/Second Language/CDK/Terraform options) (-h | -l | -c | -t))
```suggestion
#Adds Options for the following: ((Help/Second Language/CDK/Terraform options) (-h | -l | -c | -t))
```

2021-05-01 05:07 UTC, MarciaRieferJohnston approved these changes

2021-05-01 05:27 UTC, MarciaRieferJohnston requested changes
I made small edits in several places (a typo fix, URL updates, etc.)

2021-05-01 05:27 UTC, MarciaRieferJohnston commented on .specific/.cdk/cost.adoc
> +TIP: After you deploy the Quick Start, https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-gettingstarted-turnonreports.html[create AWS Cost and Usage Reports^] to deliver bi
```suggestion
TIP: After you deploy the Quick Start, create  https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-gettingstarted-turnonreports.html[AWS Cost and Usage Reports^] to deliver billing metrics to an Amazon Simple Storage Service (Amazon S3) bucket in your account. These reports provide cost estimates based on usage throughout each month and aggregate the data at the end of the month. For more information, see https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html[What are AWS Cost and Usage Reports?^]
```

2021-05-01 05:27 UTC, MarciaRieferJohnston commented on .specific/.terraform/cost.adoc
> +TIP: After you deploy the Quick Start, https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-gettingstarted-turnonreports.html[create AWS Cost and Usage Reports^] to deliver bi
```suggestion
TIP: After you deploy the Quick Start, create https://docs.aws.amazon.com/awsaccountbilling/latest/aboutv2/billing-reports-gettingstarted-turnonreports.html[AWS Cost and Usage Reports^] to deliver billing metrics to an Amazon Simple Storage Service (Amazon S3) bucket in your account. These reports provide cost estimates based on usage throughout each month and aggregate the data at the end of the month. For more information, see https://docs.aws.amazon.com/cur/latest/userguide/what-is-cur.html[What are AWS Cost and Usage Reports?^]
```

2021-05-01 05:27 UTC, MarciaRieferJohnston commented on .specific/.cdk/deploy_steps.adoc
> +To deploy this Quick Start, use AWS CDK. For more information, see https://docs.aws.amazon.com/cdk/latest/guide/work-with.html[Working with the AWS CDK].
```suggestion
To deploy this Quick Start, use AWS CDK. For more information, see https://docs.aws.amazon.com/cdk/latest/guide/work-with.html[Working with the AWS CDK^].
```

2021-05-01 05:27 UTC, MarciaRieferJohnston commented on .specific/.cdk/deploy_steps.adoc
> +To deploy this Quick Start, use AWS CDK. For more information, see https://docs.aws.amazon.com/cdk/latest/guide/work-with.html[Working with the AWS CDK].
The "^" opens the link in a new browser tab.

2021-05-01 05:34 UTC, MarciaRieferJohnston approved these changes

2021-05-03 22:27 UTC, MarciaRieferJohnston approved these changes

2021-05-03 22:35 UTC, MarciaRieferJohnston approved these changes

2021-05-03 22:35 UTC, MarciaRieferJohnston commented on .utils/create_repo_structure.sh
>            echo "Run './create_repo_structure.sh' with no options for English langauge only."
```suggestion
          echo "Run './create_repo_structure.sh' with no options for English language only."
```

2021-05-03 22:35 UTC, MarciaRieferJohnston commented on .utils/create_repo_structure.sh
>            echo "Run './create_repo_structure.sh -l' to add files for second langauge."
```suggestion
          echo "Run './create_repo_structure.sh -l' to add files for second language."
```

2021-05-09 05:01 UTC, MarciaRieferJohnston approved these changes

2021-05-12 02:06 UTC, merged