Adding Control Tower boilerplate file
aws-quickstart/quickstart-documentation-base-common pull request #147
Opened 2021-05-21 16:42 UTC by annaone

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-05-21 17:07 UTC, andrew-glenn submitted a review, later dismissed

2021-05-21 20:45 UTC, MarciaRieferJohnston requested changes
I added a few inline suggestions that can be merged directly.

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +You can deploy {partner-product-short-name} in a customized AWS Control Tower environment to help you set up a secure, multi-account AWS environment using AWS best practices. For details, see https:/
```suggestion
You can deploy {partner-product-short-name} in a customized AWS Control Tower environment to help you set up a secure, multi-account AWS environment using AWS best practices. For details, see https://aws.amazon.com/solutions/implementations/customizations-for-aws-control-tower/[Customizations for AWS Control Tower^]. 
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +You can deploy {partner-product-short-name} in a customized AWS Control Tower environment to help you set up a secure, multi-account AWS environment using AWS best practices. For details, see https:/
Adding "^" to open this link in a new tab.

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +The root directory of the {partner-product-short-name} Quick Start repo includes a *ct* folder with a manifest.yaml file to assist you with the AWS Cloud Tower deployment. This file has been customiz
```suggestion
The root directory of the {partner-product-short-name} Quick Start repo includes a `ct` folder with a `manifest.yaml` file to assist you with the AWS Control Tower deployment. This file has been customized for the {partner-product-name} Quick Start. 
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Navigate to the root directory of the {partner-product-short-name} Quick Start, and open the manifest.yaml file, located in the *ct* folder.
```suggestion
. Navigate to the root directory of the {partner-product-short-name} Quick Start, and open the `manifest.yaml` file, located in the `ct` folder.
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
```suggestion
. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different deployment options. For more information about the S3 bucket, see https://aws.amazon.com/solutions/implementations/customizations-for-aws-control-tower/[Customizations for AWS Control Tower^]. 
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +[start=4]
```suggestion
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +
```suggestion
+
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +[start=4]
Putting in a list continuation (the "+" in place of the blank line) in the previous step avoids the need to manually insert a start number.

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
Adding "^" to open this link in a new tab.

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +
Adding a [list continuation](https://docs.asciidoctor.org/asciidoc/latest/lists/continuation/) (the "+" in place of the blank line) within block elements in an ordered-list item keeps autonumbering continuous.

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Compress the manifest.yaml file and name it custom-control-tower-configuration.zip.
```suggestion
. Compress the `manifest.yaml` file and name it `custom-control-tower-configuration.zip`.
```

2021-05-21 20:45 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Upload the custom-control-tower-configuration.zip file to the S3 bucket that was created for the AWS Control Tower deployment (custom-control-tower-configuration-<accountnumber>-<region>).
```suggestion
. Upload the `custom-control-tower-configuration.zip` file to the S3 bucket that was created for the AWS Control Tower deployment (`custom-control-tower-configuration-<accountnumber>-<region>`).
```

2021-05-21 20:55 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
Is Control Tower the intended link and link text here?

2021-05-22 02:23 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
@annaone Hi, Anna. Just making sure that you saw my question here. Seems likely that this Control Tower URL and link text got pasted in where you probably meant to put an S3-related link?

2021-05-22 10:50 UTC, annaone commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
The link is correct, but we can just remove it, since we already have a pointer to that page earlier.

2021-05-22 18:46 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
```suggestion
. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different deployment options. 
```

2021-05-22 18:46 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
Done.

2021-05-22 18:49 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
```suggestion
. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different deployment options.
```

2021-05-22 18:53 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
```suggestion
. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different deployment options.
```

2021-05-22 18:55 UTC, MarciaRieferJohnston commented on deploy_control_tower.adoc
> +. Confirm that the `resource_file` attribute points to the public S3 bucket for the {partner-product-name} Quick Start. Using a public S3 bucket ensures a consistent code base across the different de
@annaone Hi, Anna. I tried several times to delete that sentence and merge, but GitHub isn't letting me merge the suggested change. I get the message "Outdated suggestions cannot be applied." I'll see if I can find a way. If you get to it first, please go ahead. Ping me, and I'll approve it right away.

2021-05-22 19:30 UTC, MarciaRieferJohnston approved these changes

2021-05-22 20:05 UTC, andrew-glenn approved these changes

2021-05-22 20:05 UTC, merged