Minor revisions to text and links
aws-quickstart/quickstart-documentation-base-common pull request #157
Opened 2021-08-03 23:39 UTC by DelfinGala

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-03 23:40 UTC, andrew-glenn approved these changes

2021-08-04 04:47 UTC, MarciaRieferJohnston requested changes

2021-08-04 04:47 UTC, MarciaRieferJohnston commented on .specific/_settings.adoc
> +// Uncomment the following attribute if you are deploying a CDK Quick Start. Ensure to comment out :parameters_as_appendix: also.
```suggestion
// Uncomment the following attribute if you are deploying a CDK Quick Start. Comment out :parameters_as_appendix: also.
```

2021-08-04 04:47 UTC, MarciaRieferJohnston commented on .specific/_settings.adoc
> +// Uncomment the following attribute if you are deploying a Terraform Quick Start. Ensure to comment out :parameters_as_appendix: also.
```suggestion
// Uncomment the following attribute if you are deploying a Terraform Quick Start. Comment out :parameters_as_appendix: also.
```

2021-08-04 04:47 UTC, MarciaRieferJohnston commented on .specific/_settings.adoc
> +// Uncomment the following two attributes if you are deploying a Terraform Quick Start. Ensure to comment out :parameters_as_appendix: also.
```suggestion
// Uncomment the following two attributes if you are deploying a Terraform Quick Start. Comment out :parameters_as_appendix: also.
```

2021-08-04 04:47 UTC, MarciaRieferJohnston commented on .specific/deploy_steps.adoc
> +WARNING: If you deploy {partner-product-short-name} into an existing VPC, ensure that your VPC has two private subnets in different Availability Zones for the workload instances and that the subnets
@DelfinGala I'm curious about undoing the contractions. The AWS Style Guide lists "you're" and "aren't" and "doesn't" as acceptable.

2021-08-04 04:50 UTC, MarciaRieferJohnston approved these changes

2021-08-04 12:56 UTC, andrew-glenn approved these changes

2021-08-04 12:56 UTC, merged