make "Supported AWS Regions" section generic by default
aws-quickstart/quickstart-documentation-base-common pull request #162
Opened 2021-08-10 21:39 UTC by jaymccon

proposed implementation to make `Supported AWS Regions` text use a generic blurb instead of per-quickstart content that is likely to go out of date when new regions are released and services add support for regions.

Provides a way to revert back to custom text for partners that require specific statements about supported regions.

Implementation is not finalized and up for discussion. I chose the approach of a variable in `_settings.adoc` as it will allow us to change the behavior of all quick starts without having to make per-repo commits, and it allows those that wish to stick with the old regions behavior a simple way to do that.

---
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-10 21:41 UTC, jaymccon commented
@MarciaRieferJohnston @DelfinGala opened this as a work-in-progress, so you can have a look at my proposed approach prior to our discussion.

2021-08-11 02:29 UTC, MarciaRieferJohnston requested changes
@jaymccon I'm setting up a meeting for you and Daniel and me to discuss how we want to rethink our way of documenting supported AWS Regions. Thanks for your creativity and thoroughness in proposing this possible new approach.

2021-08-11 02:29 UTC, MarciaRieferJohnston commented on regions.adoc
> +
@jaymccon I'm setting up a meeting for you and Daniel and me to discuss this generic blurb and all the repercussions of changing our approach to documenting the AWS Regions. Thanks for your creativity and thoroughness in proposing this possible new approach.

2021-08-11 02:29 UTC, MarciaRieferJohnston commented on regions.adoc
> +Alternatively, you can launch the Quick Start in the desired Region and see if it works. If you get an Unrecognized resource type error, it is not supported in that Region.
```suggestion
Alternatively, you can launch the Quick Start in the desired Region and see if it works. If you get an "Unrecognized resource type" error, it is not supported in that Region.
```

2021-08-11 02:35 UTC, MarciaRieferJohnston commented
@jaymccon You mention that adding a variable in **_settings.adoc** "will allow us to change the behavior of all quick starts without having to make per-repo commits." Let's discuss how that would work. Seems like published docs would still retain their static Region lists and would require per-repo commits.

2021-08-11 17:04 UTC, jaymccon commented on planning_deployment.adoc
>  // We can also pull in Regions automatically.
this was already there before I started. It looks like there was a WIP effort to auto-populate region support content. I did not want to conflate house-keeping/cleanup with this pr. I agree this area could use a cleanup, but propose we create a separate issue/pr for housekeeping (perhaps review all of the boilerplate looking for other things that should be cleaned up and handle all in one pr)

2021-08-11 17:12 UTC, jaymccon commented
> @jaymccon You mention that adding a variable in **_settings.adoc** "will allow us to change the behavior of all quick starts without having to make per-repo commits." Let's discuss how that would work. Seems like published docs would still retain their static Region lists and would require per-repo commits.

The file will still be present in repo's, but will not be rendered as the file is only rendered if `custom_supported_regions` is added to `settings.adoc` and we will not make per repo changes to add it (so any repo wanting the custom text will need to add it). Does that make sense ?

2021-08-11 17:33 UTC, MarciaRieferJohnston commented
@jaymccon You note, "The file will still be present in repos but will not be rendered as the file is only rendered if `custom_supported_regions` is added to `settings.adoc` and we will not make per repo changes to add it (so any repo wanting the custom text will need to add it). Does that make sense?"

Yes. Still, if we want to apply this new structure to existing docs, we would need to update the boilerplate submodule, which is a kind of per-repo change. I don't know that we can (or would want to) update that submodule across all deployment guides at once. Could have unforeseen consequences, especially for older Docs 2.0 guides.

2021-08-11 17:52 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
>  // We can also pull in Regions automatically.
I see your logic. It seems germane to me, though, to delete this comment as part of this PR. I see this PR as a refresh of our Region-related content and instructions based on what we now know. (I'm not aware of other housekeeping that's needed anyhow; I submit PRs as I notice things.)

2021-08-11 23:09 UTC, MarciaRieferJohnston commented on .specific/_settings.adoc
> +// Uncomment the following attribute if you would like to provide custom text about which regions are supported in the partner-editable/regions.adoc file.
_Riffing a bit ..._ 

If you need to provide custom text for the "Supported AWS Regions" section of this guide, which should happen rarely, uncomment the following attribute. After that, any text you add to the partner-editable/regions.adoc file will appear in the generated guide along with the boilerplate info on Regions. Do not provide a list of supported Regions or other info that will go out of date when new Regions are released or when services add support for additional Regions.
-----
_As for the partner-editable/regions.adoc that partners see, how about replacing its content with this?_ 

KEEP THIS FILE BLANK normally. This file is normally excluded from the generated guide because the content now comes from boilerplate. We no longer provide a list of supported Regions or other info that will go out of date when new Regions are released or when services add support for additional Regions. If your Quick Start requires custom info to supplement the boilerplate info, uncomment the :____: attribute in the partner-editable/_settings.adoc file. Then you can add the custom info in this file.

2021-08-12 00:14 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
> +
@jaymccon How about this (replacing the existing comment and example content)?

//KEEP THIS FILE BLANK normally. By default, this file is excluded from the generated guide. The content about supported Regions now comes from boilerplate. If your Quick Start requires custom info that will not change (e.g., product is for a specific geo), uncomment the :enable_regions: attribute in the partner-editable/_settings.adoc file. Then add the custom info here. Do not list all the supported Regions or provide other info that will go out of date when new Regions are released or when services add support for additional Regions. And do not duplicate what's already documented in the boilerplate.

2021-08-12 00:36 UTC, MarciaRieferJohnston commented on planning_deployment.lang.adoc
> +// Set custom_supported_regions variable in settings.adoc to enable the regions section
```suggestion
// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```

2021-08-12 00:40 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
> +// Set custom_supported_regions variable in settings.adoc to enable partner_editable/regions.adoc
```suggestion
// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```

2021-08-12 00:46 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// Set custom_supported_regions variable in settings.adoc to enable the regions section
```suggestion
// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```

2021-08-12 00:47 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// Set custom_supported_regions variable in settings.adoc to enable the regions section
```suggestion
// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```

2021-08-12 00:50 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```suggestion
// Set the custom_supported_regions variable in settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```

2021-08-12 00:59 UTC, MarciaRieferJohnston commented on regions.adoc
> +// only included if custom_supported_regions is not set in settings.adoc
@jaymccon Please see my suggestion in .specific/regions.adoc.

2021-08-12 01:03 UTC, MarciaRieferJohnston commented on regions.adoc
> +If you want to launch the {partner-product-short-name} Quick Start in a Region other than its default Region ({default_deployment_region}), you may want to first verify that all the services it deplo
@jaymccon Per our conversation in [Quip](https://quip-amazon.com/InBVA21e1UwP/Supported-AWS-Regions-section-of-QS-docs), how about this instead?

> For any Quick Start to work in a Region other than its default Region ({default_deployment_region} in this case), all the services it deploys must be supported in that Region. You can launch the Quick Start in any Region and see if it works. If you get an “Unrecognized resource type” error, the Quick Start is not supported in that Region. 

For an up-to-date list of AWS Regions and the AWS services they support, see [AWS Regional Services](https://aws.amazon.com/about-aws/global-infrastructure/regional-product-services/).

2021-08-12 01:11 UTC, MarciaRieferJohnston commented on regions.adoc
> +Alternatively, you can launch the Quick Start in the desired Region and see if it works. If you get an "Unrecognized resource type" error, it is not supported in that Region.
Delete if you go with my suggested edit in the previous lines.

2021-08-12 02:02 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
>  * us-east-1, US East (N. Virginia) (EXAMPLE)
@jaymccon If you agree with my suggestion above, delete this example content.

2021-08-12 02:12 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
>  ifdef::template_not_all_regions[]
@jaymccon Does this variable (template_not_all_regions) still make sense to keep?

2021-08-12 08:15 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
>  // We can also pull in Regions automatically.
P.S. I appreciate your reminder to keep PRs on point. :)

2021-08-12 08:52 UTC, MarciaRieferJohnston commented
I propose that we add the deploy files (with the deployment steps) to this PR. The wording of their cross references to the "Supported AWS Regions" section needs to be tweaked since we no longer list Regions.

2021-08-12 16:28 UTC, jaymccon commented on planning_deployment.adoc
>  ifdef::template_not_all_regions[]
I'm hesitant to remove it without scanning all quick start's for its presence. Without this we can't tell where it is being used, and if we remove it will break guides that do use it. My guess that if someone went through the trouble of adding a variable they likely used it somewhere.

2021-08-12 16:30 UTC, jaymccon commented on planning_deployment.adoc
>  ifdef::template_not_all_regions[]
@andrew-glenn I see you added this, can you weigh in on whether it's safe to remove ?

2021-08-12 16:58 UTC, jaymccon commented on regions.adoc
> +// only included if custom_supported_regions is not set in settings.adoc
> Is this a new non-partner-editable file with the same name as the partner-editable file ( in the .specific folder)? And is the idea that content from one or the other regions.adoc files goes into the generated guide but not from both?

exactly right, agree that this could be called out better (or maybe the generic file renamed). Got any suggestions ?

> Also, consider moving the tip ("Certain Regions are available on an opt-in basis. ") out of the three planning_deployment*.adoc

I had it like that originally and then moved it out. I couldn't think of a reason why it would conflict with custom text (the statement is always true, regardless of how a quick start is implemented). Also while I hate having 3 files with duplicated content (we should start a separate issue to try and work out how to fix that) I also feel that having generic text in partner-editable is a bad pattern, where we do that it makes it hard(practically impossible) to update the text across the entire catalog.

That said we do it in many other places, so happy to defer to your judgement on this one and open the bigger discussion of having generic text in partner-editable files in a separate issue.

2021-08-12 17:02 UTC, jaymccon commented
@MarciaRieferJohnston I'm not against that, just a few callouts:

* the deploy* files are in the `.specifc/` folder, so will need to be manually updated in each quick start.
* the xref (`link:#_supported_aws_regions[Supported AWS Regions]` will be valid with both generic and custom text, it just doesn;t explicitly tell you what regions you can select with generic. I still think the link is useful, so you can see what error to look out for if you launch in an unsupported region.

2021-08-12 18:48 UTC, jaymccon commented on planning_deployment.adoc
>  ifdef::template_not_all_regions[]
based on https://github.com/search?q=org%3Aaws-quickstart+template_not_all_regions&type=code I don't think any quick starts are using this. I will remove. @andrew-glenn please chime in if this is not the case.

2021-08-12 18:52 UTC, andrew-glenn commented on planning_deployment.adoc
>  ifdef::template_not_all_regions[]
Free to remove, can `git revert` later if we find ourselves on the undesired side of a blast radius

2021-08-12 18:57 UTC, MarciaRieferJohnston commented on regions.adoc
> +// only included if custom_supported_regions is not set in settings.adoc
@jaymccon I propose moving this tip into the default (boilerplate) content and having it there only. I would leave it out of the custom file and keep that file completed empty of placeholder text. To me, this tip is already vague since it's not actionable. It could become nonsensical (even if it's technically true) in the context of customized text. For example if the Quick Start is targeted for one particular Region--which is a likely use case for using the custom file--this tip becomes an unhelpful headscratcher. Do you disagree?

2021-08-12 19:14 UTC, MarciaRieferJohnston commented on .specific/_settings.adoc
> +// Uncomment the following attribute if you would like to provide custom text about which regions are supported in the partner-editable/regions.adoc file.
```suggestion
// Uncomment the following attribute only if your Quick Start requires custom info (e.g., the product is limited to a specific Region and that will not change). When this attribute is uncommented, any content in the partner-editable/regions.adoc file appears in the "Supported AWS Regions" section of the generated guide instead of the boilerplate info in regions_default.adoc.
```

2021-08-12 20:19 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
> +// NOTE: This content is hidden by default.
```suggestion
// KEEP THIS FILE BLANK normally. By default, this file's content is excluded from the generated guide. The content about supported Regions now comes from the boilerplate (non-partner-editable) file regions_default.adoc.

If your Quick Start requires custom info (e.g., the product is limited to a specific Region and that will not change), uncomment the custom_supported_regions attribute in the _settings.adoc file. Add the custom info here. It then appears in the generated guide instead of the boilerplate.

Do not list all the supported Regions or provide any other info that will go out of date when new Regions are released or when services add support for more Regions.
```

2021-08-12 20:21 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
> +// Set custom_supported_regions variable in settings.adoc to enable this content, it is only recommended if the list of [un]supported regions is not expected to change (eg.: product is for specific g
```suggestion
```

2021-08-12 20:23 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
> +//Example content:
```suggestion
```

2021-08-12 20:27 UTC, jaymccon commented on regions.adoc
> +// only included if custom_supported_regions is not set in settings.adoc
Gotcha, makes sense, will move it to `regions-default.adoc` for now (although maybe we ultimately want to get rid of it entirely, I agree that it's vague and not actionable. Also, when trying to select a region that is not opted-in via the console, like what we instruct customers to do, you get directed to an explanation and provides a link to opt-in)

2021-08-12 20:37 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
>  This Quick Start supports the following Regions:
```suggestion
```

2021-08-12 20:38 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
```suggestion
```

2021-08-12 20:38 UTC, MarciaRieferJohnston commented on .specific/regions.adoc
>  * us-east-1, US East (N. Virginia) (EXAMPLE)
```suggestion
```

2021-08-12 20:50 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
>  // We can also pull in Regions automatically.
```suggestion
```

2021-08-12 23:43 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
>  // We can also pull in Regions automatically.
```suggestion
```

2021-08-12 23:43 UTC, MarciaRieferJohnston commented on planning_deployment.lang.adoc
>  // We can also pull in Regions automatically.
```suggestion=
```

2021-08-12 23:47 UTC, MarciaRieferJohnston commented on planning_deployment.lang.adoc
>  // We can also pull in Regions automatically.
```suggestion
```

2021-08-12 23:52 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// We can also pull in Regions automatically.
```suggestion
```

2021-08-12 23:57 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +TIP: Certain Regions are available on an opt-in basis. For more information, see https://docs.aws.amazon.com/general/latest/gr/rande-manage.html[Managing AWS Regions^].
```suggestion
```

2021-08-13 00:03 UTC, MarciaRieferJohnston commented on planning_deployment.lang.adoc
> +// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```suggestion
// If the "Supported AWS Regions" section requires custom content (in partner-editable/regions.adoc) instead of the boilerplate content (in regions_default.adoc), uncomment the custom_supported_regions variable in _settings.adoc.
```

2021-08-13 00:05 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
> +// Set the custom_supported_regions variable in _settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```suggestion
// If the "Supported AWS Regions" section requires custom content (in partner-editable/regions.adoc) instead of the boilerplate content (in regions_default.adoc), uncomment the custom_supported_regions variable in _settings.adoc.
```

2021-08-13 00:07 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// Set the custom_supported_regions variable in settings.adoc to include the content from regions.adoc in the "Supported AWS Regions" section.
```suggestion
// If the "Supported AWS Regions" section requires custom content (in partner-editable/regions.adoc) instead of the boilerplate content (in regions_default.adoc), uncomment the custom_supported_regions variable in _settings.adoc.
```

2021-08-13 00:13 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// If the "Supported AWS Regions" section requires custom content (in partner-editable/regions.adoc) instead of the boilerplate content (in regions_default.adoc), uncomment the custom_supported_regio
```suggestion
// If the "Supported AWS Regions" section requires custom content (in partner_editable/regions.adoc) instead of the boilerplate content (in regions_default.adoc), uncomment the custom_supported_regions variable in settings.adoc.
```

2021-08-13 00:15 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// We can also pull in Regions automatically.
```suggestion
```

2021-08-13 00:18 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// We can also pull in Regions automatically.
```suggestion
```

2021-08-13 00:34 UTC, MarciaRieferJohnston commented on regions_default.adoc
> +// only included if custom_supported_regions is not set in settings.adoc
```suggestion
// By default, the following boilerplate content populates the "Supported AWS Regions" section of the generated guide. If a Quick Start requires custom content instead (e.g., the product is limited to a specific Region and that will not change), uncomment the custom_supported_regions variable in _settings.adoc. Then enter the custom content in partner_editable/regions.adoc.
```

2021-08-13 00:41 UTC, MarciaRieferJohnston commented on planning_deployment_eks_module.adoc
> +// We can also pull in Regions automatically.
```suggestion
```

2021-08-13 01:11 UTC, MarciaRieferJohnston approved these changes

2021-08-13 03:01 UTC, andrew-glenn approved these changes

2021-08-13 03:01 UTC, merged