Updated for new region setup
aws-quickstart/quickstart-documentation-base-common pull request #169
Opened 2021-08-16 18:27 UTC by troy-ameigh

*Issue #, if available:*

*Description of changes:*

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2021-08-16 18:49 UTC, MarciaRieferJohnston requested changes
@troy-ameigh While this was the edit that Paul Underwood requested in a particular CDK doc, I don't think it makes sense as a global edit in the deploy_steps.adoc file. That would introduce a duplication since we already have this information under "Launch the Quick Start" by default. The CDK content was an exception.

2021-09-03 21:30 UTC, MarciaRieferJohnston commented on .specific/.cdk/deploy_steps.adoc
> +. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is buil
```suggestion
. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default. For more information, see link:#_supported_regions[Supported Regions] earlier in this guide.
```

2021-09-03 21:31 UTC, MarciaRieferJohnston commented on .specific/.cdk/deploy_steps.adoc
> +. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is buil
```suggestion
. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default. For more information, see link:#_supported_aws_regions[Supported AWS Regions] earlier in this guide.
```

2021-09-03 21:32 UTC, MarciaRieferJohnston commented on .specific/.cdk/deploy_steps.adoc
> +. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is buil
```suggestion
. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default. For more information, see link:#_supported_aws_regions[Supported AWS Regions] earlier in this guide.
```

2021-09-03 21:36 UTC, MarciaRieferJohnston approved these changes

2021-09-03 21:39 UTC, MarciaRieferJohnston commented on .specific/.cdk/deploy_steps.adoc
> +. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the network infrastructure for {partner-product-name} is buil
```suggestion
. Check the AWS Region that's displayed in the upper-right corner of the navigation bar, and change it if necessary. This Region is where the infrastructure for {partner-product-name} is built. The template is launched in the {default_deployment_region} Region by default. For more information, see link:#_supported_aws_regions[Supported AWS Regions] earlier in this guide.
```

2021-09-03 21:40 UTC, MarciaRieferJohnston approved these changes

2021-09-03 22:00 UTC, censullo approved these changes

2021-09-03 22:02 UTC, merged