Updated header style of disclaimer.adoc
aws-quickstart/quickstart-documentation-base-common pull request #35
Opened 2020-08-20 18:57 UTC by MarciaRieferJohnston

Changed header style from level 3 to bold so that this header stops triggering a "section title out of sequence" warning when we generate the index.html file during doc review.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-09-10 21:55 UTC, censullo approved these changes

2020-09-11 00:21 UTC, jaymccon commented
The merge conflicts are due my changing the base branch to main, will try to get those resolved shortly.

2020-09-24 18:14 UTC, jaymccon approved these changes

2020-09-30 14:24 UTC, andrew-glenn requested changes

2020-09-30 14:24 UTC, andrew-glenn commented on .specific/additional_info.adoc
> +== Postdeployment steps
"Post deployment" / "Post-deployment" is an industry accepted term. Please do not deviate.

2020-09-30 14:24 UTC, andrew-glenn requested changes

2020-09-30 14:24 UTC, andrew-glenn commented on disclaimer.adoc
> -==== Notices
Please retain this indentation level.

2020-09-30 22:11 UTC, MarciaRieferJohnston commented on .specific/additional_info.adoc
> +== Postdeployment steps
@andrew-glenn Thanks for this feedback. The tech writers can see aligning on "post-deployment" (despite the no-hyphen guideline) after reviewing AWS usage elsewhere. The current boilerplate heading is "Post deployment steps." I'll replace the space with a hyphen.

2020-10-01 20:20 UTC, andrew-glenn commented
_Discussed with Marcia out-of-band. This PR is in a weird state with no clear path forward, due to an unknown base. Asking her to manually pluck any relevant changes into a new PR. Closing._

2020-10-01 20:20 UTC, closed without merging