Update planning_deployment.adoc
aws-quickstart/quickstart-documentation-base-common pull request #47
Opened 2020-08-26 21:15 UTC by MarciaRieferJohnston

Acrolinx says to avoid using the word "action" when referring to an AWS operation. Vinod confirms that it makes sense to remove the word here.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-08-26 22:12 UTC, dowen12 submitted a review, later dismissed

2020-08-26 22:12 UTC, dowen12 commented on planning_deployment.adoc
>  //todo: scope of least-privilege
This needs to be removed from here and should not be in the boilerplate files.

2020-08-26 22:55 UTC, vsnyc commented on planning_deployment.adoc
>  //todo: scope of least-privilege
I think we can resolve this comment for this PR and look only at the change proposed. @andrew-glenn may have left that as a placeholder for future work to automatically generate minimum privileges required to launch a quick start.

2020-08-26 23:17 UTC, andrew-glenn commented on planning_deployment.adoc
>  //todo: scope of least-privilege
This was a placeholder I put in there. It's out of scope for this PR.

2020-08-27 00:16 UTC, vsnyc commented on planning_deployment.adoc
>  //todo: scope of least-privilege
Agree

2020-08-27 00:18 UTC, vsnyc submitted a review, later dismissed
Looks good to me.

2020-09-10 00:21 UTC, troy-ameigh approved these changes

2020-09-10 13:05 UTC, davmayd approved these changes

2020-09-14 19:37 UTC, censullo approved these changes

2020-09-16 20:21 UTC, DelfinGala approved these changes

2020-09-30 00:48 UTC, andrew-glenn requested changes
"post deployment" / "post-deployment" is an industry accepted term. Technical context is lost when it's condensed.

2020-09-30 14:19 UTC, andrew-glenn approved these changes

2020-09-30 14:21 UTC, dowen12 approved these changes

2020-09-30 14:22 UTC, merged