Docs edit
aws-quickstart/quickstart-documentation-base-common pull request #62
Opened 2020-09-16 19:40 UTC by censullo

Updated APN -> AWS Partner language in overview.adoc.

2020-09-30 00:44 UTC, andrew-glenn requested changes
"post deployment" / "post-deployment" is an industry accepted term. Technical context is lost when it's condensed.

2020-09-30 14:29 UTC, andrew-glenn commented
I've removed the additional content that found its way into the `docs-edit` branch. Those additional changes are being reviewed in PR #35. Chris' original commits are the only thing in-scope.

2020-09-30 14:37 UTC, dowen12 requested changes

2020-09-30 14:37 UTC, dowen12 commented on deployment_steps.adoc
> +[start=1]
On this, as the docs currently stand, this allows the numbering to continue from 4 to 5 once the param tables are added between those steps. If the tables are moved to an appendix, then we either need to have the numbering continue the flow with no 'start' or we need a new heading if we are starting from 1 again.
Can you confirm this was tested and is resolved to looking like it should after the changes?

2020-09-30 14:43 UTC, andrew-glenn submitted a review, later dismissed

2020-09-30 21:56 UTC, MarciaRieferJohnston commented
> "post deployment" / "post-deployment" is an industry accepted term. Technical context is lost when it's condensed.

@andrew-glenn Thanks for this feedback. The tech writers can see aligning on "post-deployment" (despite the no-hyphen guideline) after reviewing AWS usage elsewhere. The current boilerplate heading is "Post deployment steps." I'll replace the space with a hyphen.

2020-10-01 19:55 UTC, MarciaRieferJohnston commented on deployment_steps.adoc
> +[start=1]
👍  Continued autonumbering would be ideal--this isn't 1 and not always 5.

2020-10-14 20:12 UTC, censullo commented on deployment_steps.adoc
> +[start=1]
Yes I agree with Marcia; continued autonumbering.

2020-10-14 20:18 UTC, jaymccon commented on deployment_steps.adoc
> +[start=1]
yup, I had to add `:custom_number_of_deploy_steps:` option for eks docs to get around incorrect numbering. It's not a great workaround because I had to move all the boilerplate content from this file into partner_editable.

2020-10-15 17:57 UTC, MarciaRieferJohnston requested changes
@censullo Hi, Chris. Everything in here looks good except the edit to start over at step 1. (I've submitted issue 65 in this repo to request that we replace hardcoded step numbers like this with automatic sequencing.) For now, please change that back to what it was so that we can approve the rest of these edits. Thanks!

2020-10-15 18:45 UTC, MarciaRieferJohnston approved these changes

2020-10-22 16:36 UTC, dowen12 approved these changes

2020-10-22 18:15 UTC, merged