Update overview_target_and_usage.adoc
aws-quickstart/quickstart-documentation-base-common pull request #75
Opened 2020-10-01 21:35 UTC by MarciaRieferJohnston

Revised per conversations with Daniel, Tony V, and Andrew Glenn.

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

2020-10-03 14:18 UTC, andrew-glenn requested changes

2020-10-03 14:18 UTC, andrew-glenn commented on .specific/_settings.adoc
> +:doc-month: October
As a policy, this will be replaced each time. I don't want to start a precedent where we are updating this every 30days.

2020-10-03 14:18 UTC, andrew-glenn commented on .specific/architecture.adoc
> +default parameters builds the following {partner-product-short-name} environment in the
Please leave this as-is. Italics highlight the partner company's name.

2020-10-03 14:18 UTC, andrew-glenn commented on .specific/architecture.adoc
> +.Quick Start architecture for {partner-product-short-name} on AWS
See above

2020-10-03 14:18 UTC, andrew-glenn commented on .specific/architecture.adoc
> +** <item>.
Please remove. The text preceding this is most common across all projects, and doesn't necessarily require further edits. Adding this text forces each contributor in the future to edit this file for the explicit purpose of removing this content, when otherwise no edits are needed here.

2020-10-03 14:18 UTC, andrew-glenn commented on .specific/deployment_options.adoc
> +* *Deploy {partner-product-short-name} into a new VPC*. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, bastion hosts, and other infrastructure
_end to end deployment_ is accurate. Please restore

2020-10-03 14:18 UTC, andrew-glenn commented on planning_deployment.adoc
> +// We can also pull in Regions automatically.
No need to capitalize regions in a comment that no one will publicly see

2020-10-03 20:46 UTC, MarciaRieferJohnston commented on .specific/_settings.adoc
> +:doc-month: October
@andrew-glenn Agreed. My main thought was that a template quickly looks dated when it has real dates in the placeholder spots. I'll resubmit this, treating this date placeholder text the same way we treat the placeholder text above it.

2020-10-03 21:05 UTC, MarciaRieferJohnston commented on .specific/architecture.adoc
> +default parameters builds the following {partner-product-short-name} environment in the
@andrew-glenn I discussed this with the tech writers before I put the edit in. We don't italicize the partner or product name here or anywhere else in the guide.

2020-10-03 21:08 UTC, MarciaRieferJohnston commented on .specific/architecture.adoc
> +.Quick Start architecture for {partner-product-short-name} on AWS
We don't use italics here.

2020-10-03 21:32 UTC, MarciaRieferJohnston commented on .specific/architecture.adoc
> +** <item>.
The bulleted list in the boilerplate is not accurately structured. I've revised to align the structure with our standard. As for the placeholder text, this comes from the Word template. Since much of this text near the top of the list stays nearly identical from one guide to another, our template has traditionally provided the wording to make it easy for authors to get started. Which phrases, in particular, do you want to see deleted?

2020-10-03 21:42 UTC, MarciaRieferJohnston commented on .specific/deployment_options.adoc
> +* *Deploy {partner-product-short-name} into a new VPC*. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, bastion hosts, and other infrastructure
I propose leaving it deleted. The AWS style guide lists "end-to-end" as jargon to avoid. Whatever needs to be described comes in the sentences that follow the bold phrase.

2020-10-03 23:12 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
> +// We can also pull in Regions automatically.
Understood. I wasn't thinking of it as public text. Since I was in that file anyhow, my thought was that the more often people see "Regions" capitalized in descriptions (as it almost always needs to be in public AWS text), the more normal it looks. And the more normal it looks, the more likely developers are to capitalize it in public text, leaving less for editors to do. I'm all for putting myself out of a job. :)

2020-10-03 23:47 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
> +// We can also pull in Regions automatically.
Understood. Comments aren't the focus of our editing. Since I was right there anyhow, my thought was that the more often devs see "Regions" capitalized in descriptions, the more normal it looks to them. And the more normal it looks, the more likely they are to capitalize it in their public AWS text (since it almost always needs to be uppercase). Every time "Region" comes to the editors already capitalized in public text, it leaves one less thing for us to change. Speeding up launches, one "R" at a time. :)

2020-10-03 23:47 UTC, MarciaRieferJohnston commented on .specific/deployment_options.adoc
> +* *Deploy {partner-product-short-name} into a new VPC*. This option builds a new AWS environment consisting of the VPC, subnets, NAT gateways, security groups, bastion hosts, and other infrastructure
I propose leaving it deleted. The AWS style guide lists "end-to-end" as jargon to avoid. Whatever needs to be described comes in the sentences that follow the concise bold phrase.

2020-10-03 23:48 UTC, MarciaRieferJohnston commented on .specific/architecture.adoc
> +** <item>.
The bulleted list in the current boilerplate is not accurately structured. I've revised it to align the structure with our standard list, adding bullets and subbullets where they were missing. The placeholder text was already here, brought in from the Word template. We provide this text at the top of the list because it's so common from one guide to another. The idea is to save authors from having to go copy and paste it. If it doesn't apply, they delete it, same as they do throughout the boilerplate files.

Do certain phrases here need to be deleted?

2020-10-03 23:48 UTC, MarciaRieferJohnston commented on .specific/architecture.adoc
> +default parameters builds the following {partner-product-short-name} environment in the
I had discussed this with the tech writers before I put the edit in. We don't italicize the partner or product name here or anywhere else in the guide (although the bylines are italicized on the cover).

2020-10-03 23:49 UTC, MarciaRieferJohnston commented on .specific/architecture.adoc
> +default parameters builds the following {partner-product-short-name} environment in the
I had discussed this with the tech writers before I put the edit in. We don't italicize the partner or product name here or anywhere else in body text.

2020-10-03 23:54 UTC, MarciaRieferJohnston commented on planning_deployment.adoc
> +// We can also pull in Regions automatically.
Understood. Comments aren't the focus of our editing, and we don't have to make this edit. I did it since I was right there anyhow. My thought was that the more often devs see "Regions" capitalized in descriptions, the more normal it looks to them. And the more normal it looks, the more likely they are to capitalize it in their public AWS text. Every time "Region" comes to the editors already capitalized in public text, we have one less thing to change. Scaling ourselves, one "R" at a time. :)

2020-10-05 12:57 UTC, annaone commented on .specific/architecture.adoc
> +default parameters builds the following {partner-product-short-name} environment in the
Andrew - I agree with Marcia that we need to remove the italics around the Partner's name (per Amazon style). The text alone should be sufficient to highlight Partners and their contributions to the Quick Start.

2020-10-05 12:58 UTC, annaone commented on .specific/architecture.adoc
> +.Quick Start architecture for {partner-product-short-name} on AWS
See above comment.

2020-10-05 17:51 UTC, annaone commented on .specific/architecture.adoc
> +** <item>.
I'm fine with Marcia's suggestion, since we want to make sure we structure the bullets in the correct way.

2020-10-05 18:37 UTC, censullo commented on .specific/architecture.adoc
> +default parameters builds the following {partner-product-short-name} environment in the
Yes, I agree with removing the italics around the partner's name.

2020-10-05 18:38 UTC, censullo commented on .specific/architecture.adoc
> +.Quick Start architecture for {partner-product-short-name} on AWS
No italics.

2020-10-05 18:41 UTC, censullo commented on planning_deployment.adoc
> +// We can also pull in Regions automatically.
This is fine to leave as it is not public - but, when I was first starting  - not starting like I am now, but really first getting started, I was confused as to if this should be capitalized because I saw it lower case here.

2020-10-05 19:18 UTC, annaone approved these changes

2020-10-05 19:21 UTC, andrew-glenn commented
closing and re-opening to get Tech-writers as owners.

2020-10-05 19:21 UTC, censullo approved these changes

2020-10-05 19:23 UTC, annaone approved these changes

2020-10-05 19:24 UTC, censullo approved these changes

2020-10-05 19:25 UTC, andrew-glenn approved these changes
deferring to TW consensus

2020-10-05 19:27 UTC, gargana approved these changes
LGTM! Ship it

2020-10-05 19:27 UTC, merged